<?php
    require("connect.php");
    $questionId=$_POST['courseID'];
    session_start();
    $req_interesser = "Insert into signin values(:courseID , :collabId)";
    $stmt_interesser=$bdd->prepare($req_interesser);
    $stmt_interesser->bindParam(":courseID",$questionId,PDO::PARAM_INT);
    $stmt_interesser->bindParam(":collabId",$_SESSION['id'],PDO::PARAM_INT);
    $stmt_interesser->execute();
    $req_nom_collab = "SELECT firstName, familyName FROM collaborator where collaboratorID = :collabId";
    $stmt_nom_collab=$bdd->prepare($req_nom_collab);
    $stmt_nom_collab->bindParam(":collabId",$_SESSION['id'],PDO::PARAM_INT);
    $stmt_nom_collab->execute();
    $first_last_name = $stmt_nom_collab->fetch(PDO::FETCH_ASSOC);
    $full_name = $first_last_name["familyName"]." ".$first_last_name["firstName"];
    $message_notification = $full_name." vient de s'interesser a votre formation.";
    $req_notification= "Insert into notifications (message) values (:message)";
    $stmt_notification=$bdd->prepare($req_notification);
    $stmt_notification->bindParam(":message",$message_notification,PDO::PARAM_STR);
    $stmt_notification->execute();
    $notificationId = $bdd->lastInsertId();
    $req_formation_creator = "SELECT createdBy FROM trainingprogram where courseID = :courseID";
    $stmt_formation_creator=$bdd->prepare($req_formation_creator);
    $stmt_formation_creator->bindParam(":courseID",$questionId,PDO::PARAM_INT);
    $stmt_formation_creator->execute();
    $formation_creator = $stmt_formation_creator->fetch();
    $req_notification_link = "INSERT INTO collabnotification (collaboratorID, notificationID) values (:collabID , :notifID)";
    $stmt_notification_link=$bdd->prepare($req_notification_link);
    $stmt_notification_link->bindParam(":collabID",$formation_creator['createdBy'],PDO::PARAM_INT);
    $stmt_notification_link->bindParam(":notifID",$notificationId,PDO::PARAM_INT);
    $stmt_notification_link->execute();